### ISSUE TITLE
history 공간 미리 할당하고 그동안의 히스토리를 통째로 넘겨주기

### ISSUE THREAD

**Issue by javelinsman** [javelinsman/CHIpotle#6]

**Comment by winimus** [comment]
가장 최근 5개 히스토리의 from / to 를 array로 만들어줘서 주면 제일 좋지만 그게 아니라면 그냥 가장 최근의 히스토리 5개만 던져주면 됨.

**Comment by winimus** [comment]
그리고 History에 Prop으로 Width 정보도 같이 주면 그거에 맞춰서 svgWidth 맞추는 게 좋을 것 같음.
